[package]
name = "game_prototype"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty_engine = "4.0"

[build-dependencies]
syn = { version = "1", features = ["full"] }
quote = "1"
proc-macro2 = "1"
